### ISSUE TITLE
Error while render the template

### ISSUE THREAD

**Issue by msdeek** [OCA/account-financial-reporting#1039]
[QWeb](https://www.egfd.com.eg/report/html/account_financial_report.general_ledger?options=%7B%22wizard_id%22%3A11%2C%22date_from%22%3A%222023-01-01%22%2C%22date_to%22%3A%222023-04-29%22%2C%22only_posted_moves%22%3Afalse%2C%22hide_account_at_0%22%3Afalse%2C%22foreign_currency%22%3Atrue%2C%22company_id%22%3A1%2C%22account_ids%22%3A%5B%5D%2C%22partner_ids%22%3A%5B%5D%2C%22grouped_by%22%3A%22partners%22%2C%22cost_center_ids%22%3A%5B%5D%2C%22show_cost_center%22%3Atrue%2C%22journal_ids%22%3A%5B%5D%2C%22centralize%22%3Atrue%2C%22fy_start_date%22%3A%222023-01-01%22%2C%22unaffected_earnings_account%22%3A173%2C%22account_financial_report_lang%22%3A%22en_US%22%2C%22domain%22%3A%5B%5D%7D&context=%7B%22lang%22%3A%22en_US%22%2C%22tz%22%3A%22Africa%2FCairo%22%2C%22uid%22%3A2%2C%22allowed_company_ids%22%3A%5B1%5D%2C%22active_model%22%3A%22general.ledger.report.wizard%22%2C%22active_id%22%3A11%2C%22active_ids%22%3A%5B11%5D%7D#error_qweb)
Error message:

Error while render the template
AttributeError: 'int' object has no attribute 'decimal_places'
Template: account_financial_report.report_general_ledger_lines
Path: /t/div/div[2]/t[6]/t[1]/div[1]/t[1]/span/t
Node: <t t-out="account_or_group_item_object[\'init_bal\'][\'bal_curr\']" t-options="{\'widget\': \'monetary\', \'display_currency\': account[\'currency_id\']}"/>
The error occurred while rendering the template account_financial_report.report_general_ledger_lines and evaluating the following expression: <t t-out="account_or_group_item_object[\'init_bal\'][\'bal_curr\']" t-options="{\'widget\': \'monetary\', \'display_currency\': account[\'currency_id\']}"/>

[Traceback](https://www.egfd.com.eg/report/html/account_financial_report.general_ledger?options=%7B%22wizard_id%22%3A11%2C%22date_from%22%3A%222023-01-01%22%2C%22date_to%22%3A%222023-04-29%22%2C%22only_posted_moves%22%3Afalse%2C%22hide_account_at_0%22%3Afalse%2C%22foreign_currency%22%3Atrue%2C%22company_id%22%3A1%2C%22account_ids%22%3A%5B%5D%2C%22partner_ids%22%3A%5B%5D%2C%22grouped_by%22%3A%22partners%22%2C%22cost_center_ids%22%3A%5B%5D%2C%22show_cost_center%22%3Atrue%2C%22journal_ids%22%3A%5B%5D%2C%22centralize%22%3Atrue%2C%22fy_start_date%22%3A%222023-01-01%22%2C%22unaffected_earnings_account%22%3A173%2C%22account_financial_report_lang%22%3A%22en_US%22%2C%22domain%22%3A%5B%5D%7D&context=%7B%22lang%22%3A%22en_US%22%2C%22tz%22%3A%22Africa%2FCairo%22%2C%22uid%22%3A2%2C%22allowed_company_ids%22%3A%5B1%5D%2C%22active_model%22%3A%22general.ledger.report.wizard%22%2C%22active_id%22%3A11%2C%22active_ids%22%3A%5B11%5D%7D#error_traceback)
Traceback (most recent call last):
  File "<802>", line 1080, in template_802
  File "<802>", line 292, in template_802_content
  File "/odoo/odoo-server/odoo/addons/base/models/ir_qweb.py", line 2400, in _get_widget
    content = converter.value_to_html(value, field_options)
  File "/odoo/odoo-server/odoo/addons/base/models/ir_qweb_fields.py", line 448, in value_to_html
    fmt = "%.{0}f".format(display_currency.decimal_places)
AttributeError: 'int' object has no attribute 'decimal_places'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/odoo/odoo-server/odoo/http.py", line 1583, in _serve_db
    return service_model.retrying(self._serve_ir_http, self.env)
  File "/odoo/odoo-server/odoo/service/model.py", line 134, in retrying
    result = func()
  File "/odoo/odoo-server/odoo/http.py", line 1610, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
  File "/odoo/odoo-server/odoo/http.py", line 1723, in dispatch
    return self.request.registry['ir.http']._dispatch(endpoint)
  File "/odoo/odoo-server/addons/website/models/ir_http.py", line 235, in _dispatch
    response = super()._dispatch(endpoint)
  File "/odoo/odoo-server/odoo/addons/base/models/ir_http.py", line 154, in _dispatch
    result = endpoint(**request.params)
  File "/odoo/odoo-server/odoo/http.py", line 696, in route_wrapper
    result = endpoint(self, *args, **params_ok)
  File "/odoo/custom/oca/reporting-engine/report_xlsx/controllers/main.py", line 49, in report_routes
    return super().report_routes(reportname, docids, converter, **data)
  File "/odoo/odoo-server/odoo/http.py", line 696, in route_wrapper
    result = endpoint(self, *args, **params_ok)
  File "/odoo/odoo-server/addons/web/controllers/report.py", line 39, in report_routes
    html = report.with_context(context)._render_qweb_html(reportname, docids, data=data)[0]
  File "/odoo/custom/oca/account-financial-reporting/account_financial_report/models/ir_actions_report.py", line 19, in _render_qweb_html
    return super(IrActionsReport, obj)._render_qweb_html(
  File "/odoo/odoo-server/odoo/addons/base/models/ir_actions_report.py", line 878, in _render_qweb_html
    return self._render_template(report.report_name, data), 'html'
  File "/odoo/odoo-server/odoo/addons/base/models/ir_actions_report.py", line 617, in _render_template
    return view_obj._render_template(template, values).encode()
  File "/odoo/odoo-server/addons/website/models/ir_ui_view.py", line 418, in _render_template
    return super()._render_template(template, values=values)
  File "/odoo/odoo-server/odoo/addons/base/models/ir_ui_view.py", line 2128, in _render_template
    return self.env['ir.qweb']._render(template, values)
  File "/odoo/odoo-server/odoo/tools/profiler.py", line 292, in _tracked_method_render
    return method_render(self, template, values, **options)
  File "/odoo/odoo-server/odoo/addons/base/models/ir_qweb.py", line 580, in _render
    result = ''.join(rendering)
  File "<799>", line 92, in template_799
  File "<799>", line 74, in template_799_content
  File "<799>", line 56, in template_799_t_call_0
  File "<799>", line 21, in template_799_t_call_1
  File "<800>", line 326, in template_800
  File "<800>", line 203, in template_800_content
  File "<802>", line 1086, in template_802
odoo.addons.base.models.ir_qweb.QWebException: Error while render the template
AttributeError: 'int' object has no attribute 'decimal_places'
Template: account_financial_report.report_general_ledger_lines
Path: /t/div/div[2]/t[6]/t[1]/div[1]/t[1]/span/t
Node: <t t-out="account_or_group_item_object[\'init_bal\'][\'bal_curr\']" t-options="{\'widget\': \'monetary\', \'display_currency\': account[\'currency_id\']}"/>

**Comment by pedrobaeza** [comment]
Is this fixed in #1033 ?
