### ISSUE TITLE
The error occurred while rendering the template account_financial_report.report_general_ledger_lines

### ISSUE THREAD

**Issue by Gadero5565** [OCA/account-financial-reporting#1040]
Error message:

Error while render the template
AttributeError: 'int' object has no attribute 'decimal_places'
Template: account_financial_report.report_general_ledger_lines
Path: /t/div/div[2]/t[6]/t[1]/div[1]/t[2]/span/t
Node: <t t-raw="account_or_group_item_object[\'init_bal\'][\'bal_curr\']" t-options="{\'widget\': \'monetary\', \'display_currency\': account[\'currency_id\']}"/>

The error occurred while rendering the template account_financial_report.report_general_ledger_lines and evaluating the following expression: <t t-raw="account_or_group_item_object[\'init_bal\'][\'bal_curr\']" t-options="{\'widget\': \'monetary\', \'display_currency\': account[\'currency_id\']}"/>

**Comment by pedrobaeza** [comment]
Duplicated of #1039

**Comment by Gadero5565** [comment]
i pulled the update about res.currency but this error happened :
Traceback (most recent call last):
  File "C:\odoo\odoo\http.py", line 1583, in _serve_db
    return service_model.retrying(self._serve_ir_http, self.env)
  File "C:\odoo\odoo\service\model.py", line 134, in retrying
    result = func()
  File "C:\odoo\odoo\http.py", line 1610, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
  File "C:\odoo\odoo\http.py", line 1723, in dispatch
    return self.request.registry['ir.http']._dispatch(endpoint)
  File "C:\odoo\odoo\addons\base\models\ir_http.py", line 154, in _dispatch
    result = endpoint(**request.params)
  File "C:\odoo\odoo\http.py", line 696, in route_wrapper
    result = endpoint(self, *args, **params_ok)
  File "c:\odoo\custom\erp_zad16\report_xlsx\controllers\main.py", line 49, in report_routes
    return super().report_routes(reportname, docids, converter, **data)
  File "C:\odoo\odoo\http.py", line 696, in route_wrapper
    result = endpoint(self, *args, **params_ok)
  File "c:\odoo\addons\web\controllers\report.py", line 39, in report_routes
    html = report.with_context(context)._render_qweb_html(reportname, docids, data=data)[0]
  File "c:\odoo\custom\erp_zad16\account_financial_report\models\ir_actions_report.py", line 20, in _render_qweb_html
    report_ref, docids, data=data
  File "c:\odoo\custom\erp_zad16\dynamic_odoo\models\ir_actions.py", line 46, in _render_qweb_html
    return super(IrActionsReport, self.with_context(REPORT_ID=self.search([('report_name', '=', report_ref)]).id))._render_qweb_html(report_ref, docids, data=data)
  File "C:\odoo\odoo\fields.py", line 5023, in __get__
    raise ValueError("Expected singleton: %s" % record)
ValueError: Expected singleton: ir.actions.report(565, 566)
