### ISSUE TITLE
Error when recording accounting notes with analytical distribution

### ISSUE THREAD

**Issue by JoseNicols** [OCA/account-financial-reporting#1228]
## Module
account_financial_report

## Describe the bug

When adding two or more analytical accounts from different analytical plans, the sig is marked. mistake :
RPC_ERROR
Odoo Server Error
Traceback (most recent call last):
  File "/home/odoo/src/odoo/odoo/http.py", line 1783, in _serve_db
    return service_model.retrying(self._serve_ir_http, self.env)
  File "/home/odoo/src/odoo/odoo/service/model.py", line 133, in retrying
    result = func()
  File "/home/odoo/src/odoo/odoo/http.py", line 1810, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
  File "/home/odoo/src/odoo/odoo/http.py", line 2014, in dispatch
    result = self.request.registry['ir.http']._dispatch(endpoint)
  File "/home/odoo/src/odoo/odoo/addons/base/models/ir_http.py", line 222, in _dispatch
    result = endpoint(**request.params)
  File "/home/odoo/src/odoo/odoo/http.py", line 759, in route_wrapper
    result = endpoint(self, *args, **params_ok)
  File "/home/odoo/src/odoo/addons/web/controllers/dataset.py", line 24, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/home/odoo/src/odoo/addons/web/controllers/dataset.py", line 20, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/odoo/src/odoo/odoo/api.py", line 468, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/home/odoo/src/odoo/odoo/api.py", line 453, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/home/odoo/src/odoo/addons/web/models/models.py", line 71, in web_save
    self.write(vals)
  File "/home/odoo/src/odoo/addons/purchase/models/account_invoice.py", line 153, in write
    res = super(AccountMove, self).write(vals)
  File "/home/odoo/src/odoo/addons/account/models/account_move.py", line 2528, in write
    )).write(vals)
  File "/home/odoo/src/odoo/addons/mail/models/mail_thread.py", line 317, in write
    result = super(MailThread, self).write(values)
  File "/home/odoo/src/odoo/addons/mail/models/mail_activity_mixin.py", line 250, in write
    return super(MailActivityMixin, self).write(vals)
  File "/home/odoo/src/odoo/odoo/models.py", line 4424, in write
    field.write(self, value)
  File "/home/odoo/src/odoo/odoo/fields.py", line 4337, in write
    self.write_batch([(records, value)])
  File "/home/odoo/src/odoo/odoo/fields.py", line 4358, in write_batch
    self.write_real(records_commands_list, create)
  File "/home/odoo/src/odoo/odoo/fields.py", line 4547, in write_real
    flush()
  File "/home/odoo/src/odoo/odoo/fields.py", line 4503, in flush
    comodel.create(to_create)
  File "<decorator-gen-212>", line 2, in create
  File "/home/odoo/src/odoo/odoo/api.py", line 415, in _model_create_multi
    return create(self, arg)
  File "/home/odoo/src/odoo/addons/account/models/account_move_line.py", line 1594, in create
    lines._check_constrains_account_id_journal_id()
  File "/home/odoo/src/odoo/addons/account/models/account_move_line.py", line 1265, in _check_constrains_account_id_journal_id
    self.flush_recordset()
  File "/home/odoo/src/odoo/odoo/models.py", line 6332, in flush_recordset
    self._recompute_recordset(fnames)
  File "/home/odoo/src/odoo/odoo/models.py", line 6915, in _recompute_recordset
    self._recompute_field(field, self._ids)
  File "/home/odoo/src/odoo/odoo/models.py", line 6929, in _recompute_field
    field.recompute(records)
  File "/home/odoo/src/odoo/odoo/fields.py", line 1367, in recompute
    apply_except_missing(self.compute_value, recs)
  File "/home/odoo/src/odoo/odoo/fields.py", line 1340, in apply_except_missing
    func(records)
  File "/home/odoo/src/odoo/odoo/fields.py", line 1389, in compute_value
    records._compute_field_value(self)
  File "/home/odoo/src/odoo/odoo/models.py", line 4893, in _compute_field_value
    fields.determine(field.compute, self)
  File "/home/odoo/src/odoo/odoo/fields.py", line 102, in determine
    return needle(*args)
  File "/home/odoo/src/user/account_financial_report/models/account_move_line.py", line 21, in _compute_analytic_account_ids
    for account_id in map(int, record.analytic_distribution):
ValueError: invalid literal for int() with base 10: '1,4'

The above server error caused the following client error:
RPC_ERROR: Odoo Server Error
    RPC_ERROR
        at makeErrorFromResponse (https://nicolsmx-financial-pruebas-15531457.dev.odoo.com/web/assets/5040e0d/web.assets_web.min.js:2888:163)
        at XMLHttpRequest.<anonymous> (https://nicolsmx-financial-pruebas-15531457.dev.odoo.com/web/assets/5040e0d/web.assets_web.min.js:2892:13)

## To Reproduce
**Affected versions**: v17 EE

1. We create a supplier invoice or accounting note 
2. We add 2 or more analytical accounts from different analytical plans in the lines
3. When trying to record we get the aforementioned error

<img width="607" alt="SCR-20240926-pvkw" src="https://github.com/user-attachments/assets/9eae816c-98ee-4193-ad75-0b1b230c1058">

<img width="945" alt="SCR-20240926-pxnf" src="https://github.com/user-attachments/assets/d4dbde0c-5483-45e2-b66d-2944213dc426">

**Expected behavior**
Let us record and validate without problem

Thks !

**Additional context**
Add any other context about the problem here. (e.g. OS, Python version, ...)

**Comment by pedrobaeza** [comment]
Fixed in #1219
