### ISSUE TITLE
Problem running the report 

### ISSUE THREAD

**Issue by beso4u** [OCA/account-financial-reporting#305]
when i am trying to run the report i am getting this msg 
any help 

File "/usr/lib/python2.7/site-packages/odoo/addons/base/ir/ir_qweb/qweb.py", line 317, in _compiled_fn
    raise e
QWebException: 'NoneType' object has no attribute 'id'
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/odoo/addons/base/ir/ir_qweb/qweb.py", line 315, in _compiled_fn
    return compiled(self, append, values, options, log)
  File "<template>", line 1, in template_website_report_layout_19814
  File "<template>", line 3, in body_call_content_19813
AttributeError: 'NoneType' object has no attribute 'id'

Error to render compiling AST
AttributeError: 'NoneType' object has no attribute 'id'
Template: website_report.layout
Path: /templates/t/t/t[4]
Node: <t t-set="x_icon" t-value="'/web/image/website/%s/favicon/' % website.id"/>

**Comment by sbidoul** [comment]
Please provide a precise description of the steps to reproduce the error.

**Comment by pedrobaeza** [comment]
No answer, so I close.
