### ISSUE TITLE
Odoo Server Error

### ISSUE THREAD

**Issue by erickoeoen** [OCA/account-financial-reporting#312]
Traceback (most recent call last):
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\http.py", line 638, in _handle_exception
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\http.py", line 675, in dispatch
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\http.py", line 331, in _call_function
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\service\model.py", line 119, in wrapper
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\http.py", line 324, in checked_call
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\http.py", line 933, in __call__
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\http.py", line 504, in response_wrap
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\addons\web\controllers\main.py", line 889, in call_button
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\addons\web\controllers\main.py", line 877, in _call_kw
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\api.py", line 681, in call_kw
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\api.py", line 672, in call_kw_multi
  File "C:\Users\erickoeoen\Documents\addons\account_financial_report_qweb\wizard\trial_balance_wizard.py", line 104, in button_export_pdf
  File "C:\Users\erickoeoen\Documents\addons\account_financial_report_qweb\wizard\trial_balance_wizard.py", line 127, in _export
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\api.py", line 752, in __getitem__
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\modules\registry.py", line 174, in __getitem__
KeyError: 'report_trial_balance_qweb'

Error Reporting Accounting Report?

**Comment by pedrobaeza** [comment]
No steps to reproduce the error, so I close. If more details are given, feel free to open a new one.
