### ISSUE TITLE
Odoo server error

### ISSUE THREAD

**Issue by sathwiksunderreddy** [OCA/account-financial-reporting#325]
Hi I have setup Odoo Saas module configuration in my system I am able to login as odoo.local
But when I am creating a Plan and entering to "Create template Database" It throughs the below error 

I tried setting the ngix time to 300000 and even changed the workers to 4(more than 3) 
still having this issue can anyone help in this regards 

Odoo Server Error:
Traceback (most recent call last):
  File "D:\New odoo\odoo-8.0-20170403\openerp\http.py", line 544, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "D:\New odoo\odoo-8.0-20170403\openerp\http.py", line 581, in dispatch
    result = self._call_function(**self.params)
  File "D:\New odoo\odoo-8.0-20170403\openerp\http.py", line 317, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "D:\New odoo\odoo-8.0-20170403\openerp\service\model.py", line 118, in wrapper
    return f(dbname, *args, **kwargs)
  File "D:\New odoo\odoo-8.0-20170403\openerp\http.py", line 314, in checked_call
    return self.endpoint(*a, **kw)
  File "D:\New odoo\odoo-8.0-20170403\openerp\http.py", line 810, in __call__
    return self.method(*args, **kw)
  File "D:\New odoo\odoo-8.0-20170403\openerp\http.py", line 410, in response_wrap
    response = f(*args, **kw)
  File "D:\New odoo\odoo-8.0-20170403\openerp\addons\web\controllers\main.py", line 948, in call_button
    action = self._call_kw(model, method, args, {})
  File "D:\New odoo\odoo-8.0-20170403\openerp\addons\web\controllers\main.py", line 936, in _call_kw
    return getattr(request.registry.get(model), method)(request.cr, request.uid, *args, **kwargs)
  File "D:\New odoo\odoo-8.0-20170403\openerp\api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "D:\New odoo\odoo-8.0-20170403\openerp\api.py", line 399, in old_api
    result = method(recs, *args, **kwargs)
  File "D:\New odoo\odoo-8.0-20170403\openerp\addons\saas_portal\models\saas_portal.py", line 344, in create_template_button
    res = self.create_template()
  File "D:\New odoo\odoo-8.0-20170403\openerp\api.py", line 266, in wrapper
    return new_api(self, *args, **kwargs)
  File "D:\New odoo\odoo-8.0-20170403\openerp\addons\saas_portal\models\saas_portal.py", line 365, in create_template
    raise Warning('Error on request: %s\nReason: %s \n Message: %s' % (req.url, res.reason, res.content))
Warning: Error on request: http://s1.odoo.local:80/saas_server/new_database
Reason: Not Found 
 Message: <html>
<head><title>404 Not Found</title></head>
<body bgcolor="white">
<center><h1>404 Not Found</h1></center>
<hr><center>nginx/1.12.0</center>
</body>
</html>

**Comment by sbidoul** [comment]
Hello,

The saas_portal portal module is not part of this project, and AFAIK is not maintained by OCA.

Please contact the author of that module for assistance.
