### ISSUE TITLE
account_financial_report_qweb access_denied

### ISSUE THREAD

**Issue by mrezki** [OCA/account-financial-reporting#414]
Hello i was installing account_financial_report_qweb on my local computer. while export to XLSX. I get error access_denied. this is log while error

Traceback (most recent call last):
  File "/opt/odoo10/odoo-custom/falinwa_branch/web/controllers/main.py", line 68, in wrap
    return f(*args, **kwargs)
  File "/opt/odoo10/odoo-custom/falinwa_branch/web/controllers/main.py", line 1463, in index
    action["report_name"], report_ids, report_data, context])
  File "/opt/odoo10/odoo10-server/odoo/http.py", line 118, in dispatch_rpc
    result = dispatch(method, params)
  File "/opt/odoo10/odoo10-server/odoo/service/report.py", line 32, in dispatch
    security.check(db,uid,passwd)
  File "/opt/odoo10/odoo10-server/odoo/service/security.py", line 13, in check
    return res_users.check(db, uid, passwd)
  File "/opt/odoo10/odoo10-server/odoo/addons/base/res/res_users.py", line 506, in check
    raise AccessDenied()

**Comment by pedrobaeza** [comment]
Please update your Odoo and module code, because this is solved in latest versions.

**Comment by EdgarNaranjo** [comment]
Hello good afternoon @mrezki . Could you solve the error? Now I've run into the same error, I've updated modules, checked dependencies, libraries and continues the same error.

Thank you
