### ISSUE TITLE
11.0:account_financial_report -  res = {**res, **foreign_currency}  SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by miquelalzanillas** [OCA/account-financial-reporting#462]
This error related to foreign_currency avoid to initialize the addon.

2018-09-18 07:12:58,470 27465 DEBUG ? odoo.http: Loading account_financial_report
2018-09-18 07:12:58,486 27465 WARNING ? py.warnings: /opt/odoo/odoo11-venv/lib/python3.4/site-packages/werkzeug/filesystem.py:63: BrokenFilesystemWarning: Detected a misconfigured UNIX filesystem: Will use UTF-8 as filesystem encoding instead of 'ascii'
  BrokenFilesystemWarning)

2018-09-18 07:12:58,615 27465 INFO ? werkzeug: 127.0.0.1 - - [18/Sep/2018 07:12:58] "GET /web?debug= HTTP/1.1" 500 -
2018-09-18 07:12:58,626 27465 ERROR ? werkzeug: Error on request:
Traceback (most recent call last):
  File "/opt/odoo/odoo11-venv/lib/python3.4/site-packages/werkzeug/serving.py", line 205, in run_wsgi
    execute(self.server.app)
  File "/opt/odoo/odoo11-venv/lib/python3.4/site-packages/werkzeug/serving.py", line 193, in execute
    application_iter = app(environ, start_response)
  File "/opt/odoo/odoo11/odoo/service/server.py", line 250, in app
    return self.app(e, s)
  File "/opt/odoo/odoo11/odoo/service/wsgi_server.py", line 164, in application
    return werkzeug.contrib.fixers.ProxyFix(application_unproxied)(environ, start_response)
  File "/opt/odoo/odoo11-venv/lib/python3.4/site-packages/werkzeug/contrib/fixers.py", line 152, in __call__
    return self.app(environ, start_response)
  File "/opt/odoo/odoo11/odoo/service/wsgi_server.py", line 154, in application_unproxied
    result = handler(environ, start_response)
  File "/opt/odoo/odoo11/odoo/http.py", line 1317, in __call__
    self.load_addons()
  File "/opt/odoo/odoo11/odoo/http.py", line 1349, in load_addons
    m = __import__('odoo.addons.' + module)
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
    
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
    
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
    
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
    
  File "/opt/odoo/odoo11/odoo/modules/module.py", line 82, in load_module
    exec(open(modfile, 'rb').read(), new_mod.__dict__)
  File "<string>", line 7, in <module>
    
  File "/opt/odoo/odoo11-custom-addons/account-financial-reporting/account_financial_report/report/__init__.py", line 11, in <module>
    from . import general_ledger_xlsx
File "/opt/odoo/odoo11-custom-addons/account_financial_report/report/general_ledger_xlsx.py", line 66
    res = {**res, **foreign_currency}
            ^
SyntaxError: invalid syntax

**Comment by pedrobaeza** [comment]
You should use Python 3.5, as Odoo is prepared for that version, but I'm not sure if this specific issue is due to that.
