### ISSUE TITLE
Ubuntu 18.04 - AccessDenied: Access denied

### ISSUE THREAD

**Issue by EdgarNaranjo** [OCA/account-financial-reporting#464]
Hello,
We are running the latest Odoo Community 10 (from git) with OCA (spain) modules.
And get  "Access Denied" to extract any XLST report from accounting

How to reproduce the issues:
1) Go to OCA Accounting reports
2) Select General Ledger
3) Introduce the range of dates
4) Select Export to XLSX
   
2018-09-20 08:51:16,115 18029 ERROR test1 odoo.addons.web.controllers.main: An exception occured during an http request
Traceback (most recent call last):
  File "... /addons/web/controllers/main.py", line 70, in wrap
    return f(*args, **kwargs)
  File "... /addons/web/controllers/main.py", line 1475, in index
    action["report_name"], report_ids, report_data, context])
  File "... /odoo/http.py", line 118, in dispatch_rpc
    result = dispatch(method, params)
  File ".../odoo/service/report.py", line 32, in dispatch
    security.check(db,uid,passwd)
  File ".../odoo/service/security.py", line 13, in check
    return res_users.check(db, uid, passwd)
  File ".../addons/base/res/res_users.py", line 507, in check
    raise AccessDenied()
AccessDenied: Access denied

**Comment by pedrobaeza** [comment]
Is this reproducible on runbot? https://runbot.odoo-community.org/runbot/91/10.0

**Comment by EdgarNaranjo** [comment]
Thank you for your quick answer.
The issue is not reproducible on runbot. On Ubuntu 16.04 neither!
It appears at Ubuntu 18.04 LTS

**Comment by pedrobaeza** [comment]
Then it seems a deployment problem. We have been running this in 18.04 without problems.
