### ISSUE TITLE
[12.0] ERROR when updating translations on account_tax_balance

### ISSUE THREAD

**Issue by primes2h** [OCA/account-financial-reporting#494]
Running the following command:

odoo-bin --update=account_tax_balance  --i18n-overwrite

I get this error (and 500 internal server error on browser):

2018-12-24 10:30:39,903 6921 INFO odoo12-test odoo.addons.base.models.ir_translation: module account_tax_balance: loading translation file (it) for language it_IT 
2018-12-24 10:30:39,903 6921 INFO odoo12-test odoo.tools.translate: loading 
/home/---------------/OCA/account-financial-reporting/account_tax_balance/i18n/it.po 
2018-12-24 10:30:39,917 6921 ERROR odoo12-test odoo.sql_db: bad query: b" INSERT INTO ir_translation(name, lang, res_id, src, type, value, module, state, comments)\n                           SELECT name, lang, res_id, src, type, value, module, state, comments\n                           FROM tmp_ir_translation_import\n                           WHERE type = 'model'\n                           AND noupdate IS NOT TRUE\n                           ON CONFLICT (type, lang, name, res_id) WHERE type = 'model'\n                            DO UPDATE SET (name, lang, res_id, src, type, value, module, state, comments) = (EXCLUDED.name, EXCLUDED.lang, EXCLUDED.res_id, EXCLUDED.src, EXCLUDED.type, EXCLUDED.value, EXCLUDED.module, EXCLUDED.state, EXCLUDED.comments);\n                       "
ERROR: ON CONFLICT DO UPDATE command cannot affect row a second time
HINT:  Ensure that no rows proposed for insertion within the same command have duplicate constrained values.
 
2018-12-24 10:30:39,919 6921 WARNING odoo12-test odoo.modules.loading: Transient module states were reset 
2018-12-24 10:30:39,920 6921 ERROR odoo12-test odoo.modules.registry: Failed to load registry 
Traceback (most recent call last):
  File "/home/---------------/OCA/OCB/odoo/modules/registry.py", line 60, in __new__
    return cls.registries[db_name]
  File "/home/---------------/OCA/OCB/odoo/tools/func.py", line 69, in wrapper
    return func(self, *args, **kwargs)
  File "/home/---------------/OCA/OCB/odoo/tools/lru.py", line 44, in __getitem__
    a = self.d[obj].me
KeyError: 'odoo12-test'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/---------------/OCA/OCB/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/---------------/OCA/OCB/odoo/modules/loading.py", line 417, in load_modules
    force, status, report, loaded_modules, update_module, models_to_check)
  File "/home/---------------/OCA/OCB/odoo/modules/loading.py", line 313, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/home/---------------/OCA/OCB/odoo/modules/loading.py", line 231, in load_module_graph
    module.with_context(overwrite=overwrite)._update_translations()
  File "/home/---------------/OCA/OCB/odoo/addons/base/models/ir_module.py", line 859, in _update_translations
    self.env['ir.translation'].load_module_terms(mod_names, filter_lang)
  File "/home/---------------/OCA/OCB/odoo/addons/base/models/ir_translation.py", line 772, in load_module_terms
    tools.trans_load(self._cr, trans_file, lang, verbose=False, module_name=module_name, context=context)
  File "/home/---------------/OCA/OCB/odoo/tools/translate.py", line 1015, in trans_load
    result = trans_load_data(cr, fileobj, fileformat, lang, verbose=verbose, module_name=module_name, context=context)
  File "/home/---------------/OCA/OCB/odoo/tools/translate.py", line 1159, in trans_load_data
    irt_cursor.finish()
  File "/home/---------------/OCA/OCB/odoo/addons/base/models/ir_translation.py", line 154, in finish
    """ % (self._model_table, self._table))
  File "/home/---------------/OCA/OCB/odoo/sql_db.py", line 148, in wrapper
    return f(self, *args, **kwargs)
  File "/home/---------------/OCA/OCB/odoo/sql_db.py", line 225, in execute
    res = self._obj.execute(query, params)
psycopg2.ProgrammingError: ON CONFLICT DO UPDATE command cannot affect row a second time
HINT:  Ensure that no rows proposed for insertion within the same command have duplicate constrained values

**Comment by pedrobaeza** [comment]
Please check on `it.po` that there are no duplicated `msgid` strings in the file.

**Comment by primes2h** [comment]
it.po file is ok.
The strange thing is that I translated the module yesterday using weblate but still no import commit since then.

https://translation.odoo-community.org/projects/account-financial-reporting-12-0/account-financial-reporting-12-0-account_tax_balance/it/

P.S.:
.pot file has still
"Project-Id-Version: Odoo Server 11.0\n"

**Comment by primes2h** [comment]
Just to let you know, no import commits also for other translations I made yesterday

e.g.
https://translation.odoo-community.org/projects/contract-11-0/contract-11-0-agreement/it/

https://translation.odoo-community.org/projects/l10n-italy-12-0/l10n-italy-12-0-l10n_it_withholding_tax/it/

**Comment by pedrobaeza** [comment]
@sbidoul is there any problem on the hourly cron?

**Comment by sbidoul** [comment]
The config (on components) was 24h. My hypothesis is that what was a global config before became a per component config with some weblate upgrade.

Anyway AFAICS your translations have been pushed to GitHub automatically.

I changed the default to 2h and updated all components.

**Comment by primes2h** [comment]
> 
> Anyway AFAICS your translations have been pushed to GitHub automatically.

In fact this is true for account_tax_balance in account-financial-reporting but not for other repositories I mentioned above (e.g. contract 11.0 and l10n_italy 12.0).
I only see some commits about it.po files creation, not translated ones. 
I had to create some in weblate prior to translating them because they didn't exists.

https://github.com/OCA/contract/commits/11.0
https://github.com/OCA/l10n-italy/commits/12.0

**Comment by primes2h** [comment]
I tried running 
odoo-bin --update=account_tax_balance --i18n-overwrite
again using updated it.po but I still get the error.

P.S.: .pot an all .po files have still wrong version set.
"Project-Id-Version: Odoo Server 11.0\n"

**Comment by sbidoul** [comment]
Hm, when pot files are out of date, look at travis.yml

https://github.com/OCA/account-financial-reporting/commit/fd2e003670fd47f8b89d06039c6fbac9fb01a8d1 should help.

**Comment by sbidoul** [comment]
@primes2h ok, that should resolve the problem with account_tax_balance.

Now about your two other addons with new translations, I don't understand why weblate is not pushing them to github. It looks like it behaves differently with new translation files? I'm not sure.

I gave push permission to the OCA Translators role, that should not create any additional risk.

Can you look in the component menu > Repository Maintenance if you have access to the `Push` button?

![image](https://user-images.githubusercontent.com/692075/50447832-2ff89580-091e-11e9-833a-79fcf64b839e.png)

**Comment by primes2h** [comment]
@sbidoul 
Yes, I see it. Thank you!
Anyway, I think that giving all translators access to that button is a bit risky. Maybe It should be better to enable reviewer role and use it for this kind of thing. That could help improving translations quality too.

P.s.: the email with workflow suggestions is still in my to-do list, please be patient. :)

**Comment by sbidoul** [comment]
> access to that button is a bit risky

What kind of risk do you see? AFAIU, it would only push things that weblate would push anyway automatically later.

> email with workflow suggestions is still in my to-do list

No worries :)

**Comment by primes2h** [comment]
> Hm, when pot files are out of date, look at travis.yml
> 
> [fd2e003](https://github.com/OCA/account-financial-reporting/commit/fd2e003670fd47f8b89d06039c6fbac9fb01a8d1) should help.

The original blocking error has gone and translation are now updated in existing databases. :-)

But now I get this instead (e.g. updating account_tax_balance only):

odoo-bin --update=account_tax_balance --i18n-overwrite


2018-12-26 15:37:55,929 27978 WARNING odoo12-pp odoo.models: The model wizard.open.tax.balances has no _description 
2018-12-26 15:37:56,088 27978 INFO odoo12-pp odoo.modules.registry: module account_tax_balance: creating or updating database tables 
2018-12-26 15:37:56,259 27978 INFO odoo12-pp odoo.modules.loading: loading account_tax_balance/wizard/open_tax_balances_view.xml 
2018-12-26 15:37:56,352 27978 INFO odoo12-pp odoo.modules.loading: loading account_tax_balance/views/account_move_view.xml 
2018-12-26 15:37:56,499 27978 ERROR odoo12-pp odoo.tools.view_validation: <string>:0:0:ERROR:RELAXNGV:RELAXNG_ERR_ATTRVALID: Element filter failed to validate attributes 
2018-12-26 15:37:56,500 27978 ERROR odoo12-pp odoo.tools.view_validation: <string>:22:0:ERROR:RELAXNGV:RELAXNG_ERR_NOELEM: Expecting an element field, got nothing 
2018-12-26 15:37:56,500 27978 ERROR odoo12-pp odoo.tools.view_validation: <string>:17:0:ERROR:RELAXNGV:RELAXNG_ERR_EXTRACONTENT: Element group has extra content: filter 
2018-12-26 15:37:56,500 27978 ERROR odoo12-pp odoo.tools.view_validation: <string>:2:0:ERROR:RELAXNGV:RELAXNG_ERR_EXTRACONTENT: Element search has extra content: field 
2018-12-26 15:37:56,500 27978 ERROR odoo12-pp odoo.tools.view_validation: Invalid XML:  Get RNG validator and validate RNG file. 
2018-12-26 15:37:56,505 27978 WARNING odoo12-pp odoo.modules.loading: Transient module states were reset 
2018-12-26 15:37:56,506 27978 ERROR odoo12-pp odoo.modules.registry: Failed to load registry 
Traceback (most recent call last):
  File "/home/----------/OCA/OCB/odoo/modules/registry.py", line 60, in __new__
    return cls.registries[db_name]
  File "/home/----------/OCA/OCB/odoo/tools/func.py", line 69, in wrapper
    return func(self, *args, **kwargs)
  File "/home/----------/OCA/OCB/odoo/tools/lru.py", line 44, in __getitem__
    a = self.d[obj].me
KeyError: 'odoo12-pp'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/----------/OCA/OCB/odoo/tools/convert.py", line 757, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/home/----------/OCA/OCB/odoo/tools/convert.py", line 662, in _tag_record
    record = model.with_context(rec_context)._load_records([data], self.mode == 'update')
  File "/home/----------/OCA/OCB/odoo/models.py", line 3778, in _load_records
    data['record'].write(data['values'])
  File "/home/----------/OCA/OCB/odoo/addons/base/models/ir_ui_view.py", line 441, in write
    return super(View, self).write(self._compute_defaults(vals))
  File "/home/----------/OCA/OCB/odoo/models.py", line 3296, in write
    fields[0].determine_inverse(records)
  File "/home/----------/OCA/OCB/odoo/fields.py", line 1104, in determine_inverse
    getattr(records, self.inverse)()
  File "/home/----------/OCA/OCB/odoo/addons/base/models/ir_ui_view.py", line 275, in _inverse_arch
    view.write(data)
  File "/home/----------/OCA/OCB/odoo/addons/base/models/ir_ui_view.py", line 441, in write
    return super(View, self).write(self._compute_defaults(vals))
  File "/home/----------/OCA/OCB/odoo/models.py", line 3259, in write
    self._write(store_vals)
  File "/home/----------/OCA/OCB/odoo/models.py", line 3403, in _write
    self._validate_fields(vals)
  File "/home/----------/OCA/OCB/odoo/models.py", line 1102, in _validate_fields
    check(self)
  File "/home/----------/OCA/OCB/odoo/addons/base/models/ir_ui_view.py", line 360, in _check_xml
    raise ValidationError(_('Invalid view %s definition in %s') % (view.name, view.arch_fs))
odoo.exceptions.ValidationError: ('Invalid view Add move type group by definition in account_tax_balance/views/account_move_view.xml', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/----------/OCA/OCB/odoo/http.py", line 1469, in dispatch
    odoo.registry(db).check_signaling()
  File "/home/----------/OCA/OCB/odoo/__init__.py", line 81, in registry
    return modules.registry.Registry(database_name)
  File "/home/----------/OCA/OCB/odoo/modules/registry.py", line 62, in __new__
    return cls.new(db_name)
  File "/home/----------/OCA/OCB/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/----------/OCA/OCB/odoo/modules/loading.py", line 417, in load_modules
    force, status, report, loaded_modules, update_module, models_to_check)
  File "/home/----------/OCA/OCB/odoo/modules/loading.py", line 313, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/home/----------/OCA/OCB/odoo/modules/loading.py", line 222, in load_module_graph
    load_data(cr, idref, mode, kind='data', package=package, report=report)
  File "/home/----------/OCA/OCB/odoo/modules/loading.py", line 68, in load_data
    tools.convert_file(cr, package.name, filename, idref, mode, noupdate, kind, report)
  File "/home/----------/OCA/OCB/odoo/tools/convert.py", line 801, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/home/----------/OCA/OCB/odoo/tools/convert.py", line 864, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/home/----------/OCA/OCB/odoo/tools/convert.py", line 763, in parse
    exc_info[2]
  File "/home/----------/OCA/OCB/odoo/tools/pycompat.py", line 86, in reraise
    raise value.with_traceback(tb)
  File "/home/----------/OCA/OCB/odoo/tools/convert.py", line 757, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/home/----------/OCA/OCB/odoo/tools/convert.py", line 662, in _tag_record
    record = model.with_context(rec_context)._load_records([data], self.mode == 'update')
  File "/home/----------/OCA/OCB/odoo/models.py", line 3778, in _load_records
    data['record'].write(data['values'])
  File "/home/----------/OCA/OCB/odoo/addons/base/models/ir_ui_view.py", line 441, in write
    return super(View, self).write(self._compute_defaults(vals))
  File "/home/----------/OCA/OCB/odoo/models.py", line 3296, in write
    fields[0].determine_inverse(records)
  File "/home/----------/OCA/OCB/odoo/fields.py", line 1104, in determine_inverse
    getattr(records, self.inverse)()
  File "/home/----------/OCA/OCB/odoo/addons/base/models/ir_ui_view.py", line 275, in _inverse_arch
    view.write(data)
  File "/home/----------/OCA/OCB/odoo/addons/base/models/ir_ui_view.py", line 441, in write
    return super(View, self).write(self._compute_defaults(vals))
  File "/home/----------/OCA/OCB/odoo/models.py", line 3259, in write
    self._write(store_vals)
  File "/home/----------/OCA/OCB/odoo/models.py", line 3403, in _write
    self._validate_fields(vals)
  File "/home/----------/OCA/OCB/odoo/models.py", line 1102, in _validate_fields
    check(self)
  File "/home/----------/OCA/OCB/odoo/addons/base/models/ir_ui_view.py", line 360, in _check_xml
    raise ValidationError(_('Invalid view %s definition in %s') % (view.name, view.arch_fs))
odoo.tools.convert.ParseError: "Invalid view Add move type group by definition in account_tax_balance/views/account_move_view.xml
None" while parsing /home/----------/OCA/account-financial-reporting/account_tax_balance/views/account_move_view.xml:29, near
<record id="view_account_move_filter" model="ir.ui.view">
    <field name="name">Add move type group by</field>
    <field name="model">account.move</field>
    <field name="inherit_id" ref="account.view_account_move_filter"/>
    <field name="arch" type="xml">
        <group expand="0" position="inside">
            <filter string="Move type" domain="[]" context="{'group_by':'move_type'}"/>
        </group>
    </field>
</record>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/----------/OCA/OCB/odoo/modules/registry.py", line 60, in __new__
    return cls.registries[db_name]
  File "/home/----------/OCA/OCB/odoo/tools/func.py", line 69, in wrapper
    return func(self, *args, **kwargs)
  File "/home/----------/OCA/OCB/odoo/tools/lru.py", line 44, in __getitem__
    a = self.d[obj].me
KeyError: 'odoo12-pp'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/----------/OCA/OCB/odoo/tools/convert.py", line 757, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/home/----------/OCA/OCB/odoo/tools/convert.py", line 662, in _tag_record
    record = model.with_context(rec_context)._load_records([data], self.mode == 'update')
  File "/home/----------/OCA/OCB/odoo/models.py", line 3778, in _load_records
    data['record'].write(data['values'])
  File "/home/----------/OCA/OCB/odoo/addons/base/models/ir_ui_view.py", line 441, in write
    return super(View, self).write(self._compute_defaults(vals))
  File "/home/----------/OCA/OCB/odoo/models.py", line 3296, in write
    fields[0].determine_inverse(records)
  File "/home/----------/OCA/OCB/odoo/fields.py", line 1104, in determine_inverse
    getattr(records, self.inverse)()
  File "/home/----------/OCA/OCB/odoo/addons/base/models/ir_ui_view.py", line 275, in _inverse_arch
    view.write(data)
  File "/home/----------/OCA/OCB/odoo/addons/base/models/ir_ui_view.py", line 441, in write
    return super(View, self).write(self._compute_defaults(vals))
  File "/home/----------/OCA/OCB/odoo/models.py", line 3259, in write
    self._write(store_vals)
  File "/home/----------/OCA/OCB/odoo/models.py", line 3403, in _write
    self._validate_fields(vals)
  File "/home/----------/OCA/OCB/odoo/models.py", line 1102, in _validate_fields
    check(self)
  File "/home/----------/OCA/OCB/odoo/addons/base/models/ir_ui_view.py", line 360, in _check_xml
    raise ValidationError(_('Invalid view %s definition in %s') % (view.name, view.arch_fs))
odoo.exceptions.ValidationError: ('Invalid view Add move type group by definition in account_tax_balance/views/account_move_view.xml', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/----------/OCA/OCB/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/----------/OCA/OCB/odoo/modules/loading.py", line 417, in load_modules
    force, status, report, loaded_modules, update_module, models_to_check)
  File "/home/----------/OCA/OCB/odoo/modules/loading.py", line 313, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/home/----------/OCA/OCB/odoo/modules/loading.py", line 222, in load_module_graph
    load_data(cr, idref, mode, kind='data', package=package, report=report)
  File "/home/----------/OCA/OCB/odoo/modules/loading.py", line 68, in load_data
    tools.convert_file(cr, package.name, filename, idref, mode, noupdate, kind, report)
  File "/home/----------/OCA/OCB/odoo/tools/convert.py", line 801, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/home/----------/OCA/OCB/odoo/tools/convert.py", line 864, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/home/----------/OCA/OCB/odoo/tools/convert.py", line 763, in parse
    exc_info[2]
  File "/home/----------/OCA/OCB/odoo/tools/pycompat.py", line 86, in reraise
    raise value.with_traceback(tb)
  File "/home/----------/OCA/OCB/odoo/tools/convert.py", line 757, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/home/----------/OCA/OCB/odoo/tools/convert.py", line 662, in _tag_record
    record = model.with_context(rec_context)._load_records([data], self.mode == 'update')
  File "/home/----------/OCA/OCB/odoo/models.py", line 3778, in _load_records
    data['record'].write(data['values'])
  File "/home/----------/OCA/OCB/odoo/addons/base/models/ir_ui_view.py", line 441, in write
    return super(View, self).write(self._compute_defaults(vals))
  File "/home/----------/OCA/OCB/odoo/models.py", line 3296, in write
    fields[0].determine_inverse(records)
  File "/home/----------/OCA/OCB/odoo/fields.py", line 1104, in determine_inverse
    getattr(records, self.inverse)()
  File "/home/----------/OCA/OCB/odoo/addons/base/models/ir_ui_view.py", line 275, in _inverse_arch
    view.write(data)
  File "/home/----------/OCA/OCB/odoo/addons/base/models/ir_ui_view.py", line 441, in write
    return super(View, self).write(self._compute_defaults(vals))
  File "/home/----------/OCA/OCB/odoo/models.py", line 3259, in write
    self._write(store_vals)
  File "/home/----------/OCA/OCB/odoo/models.py", line 3403, in _write
    self._validate_fields(vals)
  File "/home/----------/OCA/OCB/odoo/models.py", line 1102, in _validate_fields
    check(self)
  File "/home/----------/OCA/OCB/odoo/addons/base/models/ir_ui_view.py", line 360, in _check_xml
    raise ValidationError(_('Invalid view %s definition in %s') % (view.name, view.arch_fs))
odoo.tools.convert.ParseError: "Invalid view Add move type group by definition in account_tax_balance/views/account_move_view.xml
None" while parsing /home/----------/OCA/account-financial-reporting/account_tax_balance/views/account_move_view.xml:29, near
<record id="view_account_move_filter" model="ir.ui.view">
    <field name="name">Add move type group by</field>
    <field name="model">account.move</field>
    <field name="inherit_id" ref="account.view_account_move_filter"/>
    <field name="arch" type="xml">
        <group expand="0" position="inside">
            <filter string="Move type" domain="[]" context="{'group_by':'move_type'}"/>
        </group>
    </field>
</record>
2018-12-26 15:37:56,514 27978 INFO odoo12-pp werkzeug: 127.0.0.1 - - [26/Dec/2018 15:37:56] "GET /web HTTP/1.1" 500 - 748 0.478 1.983
2018-12-26 15:37:56,530 27978 ERROR odoo12-pp werkzeug: Error on request:
Traceback (most recent call last):
  File "/home/----------/OCA/venv-3.5/lib/python3.5/site-packages/werkzeug/serving.py", line 205, in run_wsgi
    execute(self.server.app)
  File "/home/----------/OCA/venv-3.5/lib/python3.5/site-packages/werkzeug/serving.py", line 193, in execute
    application_iter = app(environ, start_response)
  File "/home/----------/OCA/OCB/odoo/service/server.py", line 350, in app
    return self.app(e, s)
  File "/home/----------/OCA/OCB/odoo/service/wsgi_server.py", line 128, in application
    return application_unproxied(environ, start_response)
  File "/home/----------/OCA/OCB/odoo/service/wsgi_server.py", line 117, in application_unproxied
    result = odoo.http.root(environ, start_response)
  File "/home/----------/OCA/OCB/odoo/http.py", line 1318, in __call__
    return self.dispatch(environ, start_response)
  File "/home/----------/OCA/OCB/odoo/http.py", line 1291, in __call__
    return self.app(environ, start_wrapped)
  File "/home/----------/OCA/venv-3.5/lib/python3.5/site-packages/werkzeug/wsgi.py", line 599, in __call__
    return self.app(environ, start_response)
  File "/home/----------/OCA/OCB/odoo/http.py", line 1490, in dispatch
    response = self.get_response(httprequest, result, explicit_session)
  File "/home/----------/OCA/OCB/odoo/http.py", line 287, in __exit__
    elif self.registry:
  File "/home/----------/OCA/OCB/odoo/http.py", line 378, in registry
    return odoo.registry(self.db)
  File "/home/----------/OCA/OCB/odoo/__init__.py", line 81, in registry
    return modules.registry.Registry(database_name)
  File "/home/----------/OCA/OCB/odoo/modules/registry.py", line 62, in __new__
    return cls.new(db_name)
  File "/home/----------/OCA/OCB/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/----------/OCA/OCB/odoo/modules/loading.py", line 417, in load_modules
    force, status, report, loaded_modules, update_module, models_to_check)
  File "/home/----------/OCA/OCB/odoo/modules/loading.py", line 313, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/home/----------/OCA/OCB/odoo/modules/loading.py", line 222, in load_module_graph
    load_data(cr, idref, mode, kind='data', package=package, report=report)
  File "/home/----------/OCA/OCB/odoo/modules/loading.py", line 68, in load_data
    tools.convert_file(cr, package.name, filename, idref, mode, noupdate, kind, report)
  File "/home/----------/OCA/OCB/odoo/tools/convert.py", line 801, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/home/----------/OCA/OCB/odoo/tools/convert.py", line 864, in convert_xml_import
    obj.parse(doc.getroot(), mode=mode)
  File "/home/----------/OCA/OCB/odoo/tools/convert.py", line 763, in parse
    exc_info[2]
  File "/home/----------/OCA/OCB/odoo/tools/pycompat.py", line 86, in reraise
    raise value.with_traceback(tb)
  File "/home/----------/OCA/OCB/odoo/tools/convert.py", line 757, in parse
    self._tags[rec.tag](rec, de, mode=mode)
  File "/home/----------/OCA/OCB/odoo/tools/convert.py", line 662, in _tag_record
    record = model.with_context(rec_context)._load_records([data], self.mode == 'update')
  File "/home/----------/OCA/OCB/odoo/models.py", line 3778, in _load_records
    data['record'].write(data['values'])
  File "/home/----------/OCA/OCB/odoo/addons/base/models/ir_ui_view.py", line 441, in write
    return super(View, self).write(self._compute_defaults(vals))
  File "/home/----------/OCA/OCB/odoo/models.py", line 3296, in write
    fields[0].determine_inverse(records)
  File "/home/----------/OCA/OCB/odoo/fields.py", line 1104, in determine_inverse
    getattr(records, self.inverse)()
  File "/home/----------/OCA/OCB/odoo/addons/base/models/ir_ui_view.py", line 275, in _inverse_arch
    view.write(data)
  File "/home/----------/OCA/OCB/odoo/addons/base/models/ir_ui_view.py", line 441, in write
    return super(View, self).write(self._compute_defaults(vals))
  File "/home/----------/OCA/OCB/odoo/models.py", line 3259, in write
    self._write(store_vals)
  File "/home/----------/OCA/OCB/odoo/models.py", line 3403, in _write
    self._validate_fields(vals)
  File "/home/----------/OCA/OCB/odoo/models.py", line 1102, in _validate_fields
    check(self)
  File "/home/----------/OCA/OCB/odoo/addons/base/models/ir_ui_view.py", line 360, in _check_xml
    raise ValidationError(_('Invalid view %s definition in %s') % (view.name, view.arch_fs))
odoo.tools.convert.ParseError: "Invalid view Add move type group by definition in account_tax_balance/views/account_move_view.xml
None" while parsing /home/----------/OCA/account-financial-reporting/account_tax_balance/views/account_move_view.xml:29, near
<record id="view_account_move_filter" model="ir.ui.view">
    <field name="name">Add move type group by</field>
    <field name="model">account.move</field>
    <field name="inherit_id" ref="account.view_account_move_filter"/>
    <field name="arch" type="xml">
        <group expand="0" position="inside">
            <filter string="Move type" domain="[]" context="{'group_by':'move_type'}"/>
        </group>
    </field>
</record> - - -

**Comment by primes2h** [comment]
> Hm, when pot files are out of date, look at travis.yml
> 
> [fd2e003](https://github.com/OCA/account-financial-reporting/commit/fd2e003670fd47f8b89d06039c6fbac9fb01a8d1) should help.

I saw that the same issue (missing MAKEPOT="1") is present also in 11.0 and 10.0 versions.
Could you please update them as well? Thanks.

**Comment by sbidoul** [comment]
@primes2h 10 and 11 have TRANSIFEX=1 which is supported for backward compatibility, so these should be ok.

**Comment by primes2h** [comment]
> > access to that button is a bit risky
> 
> What kind of risk do you see? AFAIU, it would only push things that weblate would push anyway automatically later.

You are right, the risk I refer to is not about the button itself, but to the related translator role.
With current settings, translations are open to anyone registered on the website, without any kind of quality assurance.
For instance, if you finish a translation you can't be sure that anyone else change it (in a wrong way) afterwards.
To ensure quality you need guidelines, rules, context knowledge and, most important thing, a translator that knows all of them.
Imho, in some way, it's not so much different from coding.
So if code needs review why not a transation? :-)

**Comment by sbidoul** [comment]
Ok, I tend to agree translation reviewers would be nice to have. It's mostly a question of defining a process that is manageable OCA-wide. How to decide who is reviewer, etc.

**Comment by primes2h** [comment]
> Ok, I tend to agree translation reviewers would be nice to have. It's mostly a question of defining a process that is manageable OCA-wide. How to decide who is reviewer, etc.

Exactly, those things are all in the "not yet ready" email. ;-)

**Comment by primes2h** [comment]
> > Hm, when pot files are out of date, look at travis.yml
> > [fd2e003](https://github.com/OCA/account-financial-reporting/commit/fd2e003670fd47f8b89d06039c6fbac9fb01a8d1) should help.
> 
> The original blocking error has gone and translation are now updated in existing databases. :-)
> 
> But now I get this instead (e.g. updating account_tax_balance only):


Sorry, this last was my fault.
Now it works as expected.
Thanks!

**Comment by primes2h** [comment]
> @primes2h 10 and 11 have TRANSIFEX=1 which is supported for backward compatibility, so these should be ok.

Ok, thanks :+1:
