### ISSUE TITLE
[11.0] Error Aged Partner Balance when you choose details.

### ISSUE THREAD

**Issue by yung-wang** [OCA/account-financial-reporting#513]
I get this error when I choose details in the Aged Partner Balance
Sorry, but I cannot provide the database for research and I have no idea how to reproduce this in a clean database. Maybe someone can help and knows what is wrong when reading the error message.

Odoo Server Error

Traceback (most recent call last):
  File "/opt/odoo/odoo-server/odoo/addons/base/ir/ir_qweb/qweb.py", line 343, in _compiled_fn
    return compiled(self, append, new, options, log)
  File "<template>", line 1, in template_account_financial_report_report_aged_partner_balance_move_lines_3727
  File "<template>", line 46, in foreach_3726
  File "/opt/odoo/odoo-server/odoo/fields.py", line 935, in __get__
    record.ensure_one()
  File "/opt/odoo/odoo-server/odoo/models.py", line 4367, in ensure_one
    raise ValueError("Expected singleton: %s" % self)
ValueError: Expected singleton: account.partial.reconcile(9971, 9972, 9973, 9974, 9975, 9976, 9978, 9979, 9980, 9981, 9982, 9983, 9984, 9985, 9986, 9987, 9988, 9989, 9990, 9991)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/odoo/odoo-server/odoo/http.py", line 651, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo-server/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/opt/odoo/odoo-server/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/opt/odoo/odoo-server/odoo/http.py", line 693, in dispatch
    result = self._call_function(**self.params)
  File "/opt/odoo/odoo-server/odoo/http.py", line 342, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/odoo-server/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/odoo-server/odoo/http.py", line 335, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/odoo-server/odoo/http.py", line 937, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/odoo-server/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/odoo-server/addons/web/controllers/main.py", line 934, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/opt/odoo/odoo-server/addons/web/controllers/main.py", line 926, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/odoo/odoo-server/odoo/api.py", line 687, in call_kw
    return call_kw_model(method, model, args, kwargs)
  File "/opt/odoo/odoo-server/odoo/api.py", line 672, in call_kw_model
    result = method(recs, *args, **kwargs)
  File "/opt/odoo/custom/addons/account_financial_report/report/aged_partner_balance.py", line 214, in get_html
    return self._get_html()
  File "/opt/odoo/custom/addons/account_financial_report/report/aged_partner_balance.py", line 209, in _get_html
    rcontext)
  File "/opt/odoo/odoo-server/addons/website/models/ir_ui_view.py", line 113, in render
    return super(View, self).render(values, engine=engine)
  File "/opt/odoo/odoo-server/addons/web_editor/models/ir_ui_view.py", line 27, in render
    return super(IrUiView, self).render(values=values, engine=engine)
  File "/opt/odoo/odoo-server/odoo/addons/base/ir/ir_ui_view.py", line 1217, in render
    return self.env[engine].render(self.id, qcontext)
  File "/opt/odoo/odoo-server/odoo/addons/base/ir/ir_qweb/ir_qweb.py", line 57, in render
    return super(IrQWeb, self).render(id_or_xml_id, values=values, **context)
  File "/opt/odoo/odoo-server/odoo/addons/base/ir/ir_qweb/qweb.py", line 272, in render
    self.compile(template, options)(self, body.append, values or {})
  File "/opt/odoo/odoo-server/odoo/addons/base/ir/ir_qweb/qweb.py", line 345, in _compiled_fn
    raise e
  File "/opt/odoo/odoo-server/odoo/addons/base/ir/ir_qweb/qweb.py", line 343, in _compiled_fn
    return compiled(self, append, new, options, log)
  File "<template>", line 1, in template_1696_3675
  File "/opt/odoo/odoo-server/odoo/addons/base/ir/ir_qweb/qweb.py", line 345, in _compiled_fn
    raise e
  File "/opt/odoo/odoo-server/odoo/addons/base/ir/ir_qweb/qweb.py", line 343, in _compiled_fn
    return compiled(self, append, new, options, log)
  File "<template>", line 1, in template_account_financial_report_report_aged_partner_balance_base_3702
  File "<template>", line 13, in foreach_3701
  File "<template>", line 44, in foreach_3698
  File "/opt/odoo/odoo-server/odoo/addons/base/ir/ir_qweb/qweb.py", line 350, in _compiled_fn
    raise QWebException("Error to render compiling AST", e, path, node and etree.tostring(node[0], encoding='unicode'), name)
odoo.addons.base.ir.ir_qweb.qweb.QWebException: Expected singleton: account.partial.reconcile(9971, 9972, 9973, 9974, 9975, 9976, 9978, 9979, 9980, 9981, 9982, 9983, 9984, 9985, 9986, 9987, 9988, 9989, 9990, 9991)
Traceback (most recent call last):
  File "/opt/odoo/odoo-server/odoo/addons/base/ir/ir_qweb/qweb.py", line 343, in _compiled_fn
    return compiled(self, append, new, options, log)
  File "<template>", line 1, in template_account_financial_report_report_aged_partner_balance_move_lines_3727
  File "<template>", line 46, in foreach_3726
  File "/opt/odoo/odoo-server/odoo/fields.py", line 935, in __get__
    record.ensure_one()
  File "/opt/odoo/odoo-server/odoo/models.py", line 4367, in ensure_one
    raise ValueError("Expected singleton: %s" % self)
ValueError: Expected singleton: account.partial.reconcile(9971, 9972, 9973, 9974, 9975, 9976, 9978, 9979, 9980, 9981, 9982, 9983, 9984, 9985, 9986, 9987, 9988, 9989, 9990, 9991)

Error to render compiling AST
ValueError: Expected singleton: account.partial.reconcile(9971, 9972, 9973, 9974, 9975, 9976, 9978, 9979, 9980, 9981, 9982, 9983, 9984, 9985, 9986, 9987, 9988, 9989, 9990, 9991)
Template: account_financial_report.report_aged_partner_balance_move_lines
Path: /templates/t/div/t/div/div[8]/span/a
Node: <a t-att-data-domain="[('id', 'in', list(filter(lambda x: x != 'False', [str(line.move_line_id.id), str(line.move_line_id.matched_debit_ids.debit_move_id.id), str(line.move_line_id.matched_credit_ids.credit_move_id.id)])))]" t-att-data-res-model="'account.move.line'" class="o_account_financial_reports_web_action_multi" style="color: black;">
                            <t t-raw="line.amount_residual" t-options="{'widget': 'monetary', 'display_currency': res_company.currency_id}"/></a>

**Comment by JordiBForgeFlow** [comment]
@mreficent can you check?

**Comment by fclementic2c** [comment]
I cannot reproduce. I tested it on a big DB and it works fine :\

**Comment by MiquelRForgeFlow** [comment]
@yung-wang the error seems to come from the `template_account_financial_report_report_aged_partner_balance_move_lines_3727` xml template, that have a wrong code. Could you put here the code of this template?

**Comment by MiquelRForgeFlow** [comment]
No, sorry, I think I have found the error.

@yung-wang could you check if with https://github.com/OCA/account-financial-reporting/pull/514 the error is solved?

**Comment by astirpe** [comment]
This issue can be closed
