### ISSUE TITLE
Error While Installing 

### ISSUE THREAD

**Issue by Brainoids001** [OCA/account-financial-reporting#536]
i got following error while installing qweb financial report :
Traceback (most recent call last):
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\http.py", line 642, in _handle_exception
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\http.py", line 684, in dispatch
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\http.py", line 334, in _call_function
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\service\model.py", line 101, in wrapper
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\http.py", line 327, in checked_call
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\http.py", line 942, in __call__
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\http.py", line 507, in response_wrap
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\addons\web\controllers\main.py", line 896, in call_button
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\addons\web\controllers\main.py", line 884, in _call_kw
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\api.py", line 689, in call_kw
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\api.py", line 680, in call_kw_multi
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\addons\base\module\module.py", line 411, in button_immediate_install
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\addons\base\module\module.py", line 485, in _button_immediate_function
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\modules\registry.py", line 83, in new
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\modules\loading.py", line 368, in load_modules
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\modules\loading.py", line 261, in load_marked_modules
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\modules\loading.py", line 173, in load_module_graph
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\modules\loading.py", line 96, in _load_data
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\tools\convert.py", line 845, in convert_file
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\tools\convert.py", line 915, in convert_xml_import
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\tools\convert.py", line 799, in parse
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\tools\convert.py", line 707, in _tag_record
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\addons\base\ir\ir_model.py", line 1236, in _update
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\addons\base\ir\ir_ui_view.py", line 362, in create
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\models.py", line 3855, in create
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\fields.py", line 1046, in determine_inverse
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\addons\base\ir\ir_ui_view.py", line 220, in _inverse_arch
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\addons\base\ir\ir_ui_view.py", line 380, in write
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\models.py", line 3568, in write
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\models.py", line 3732, in _write
  File "C:\Program Files (x86)\Odoo 10.0\server\odoo\models.py", line 1081, in _validate_fields
ParseError: "Error while validating constraint

Field `hide_account_at_0` does not exist

Error context:
View `General Ledger`
[view_id: 1418, xml_id: n/a, model: general.ledger.report.wizard, parent_id: n/a]
None" while parsing file:///c:/program%20files%20(x86)/odoo%2010.0/server/odoo/addons/account_financial_report_qweb/wizard/general_ledger_wizard_view.xml:5, near
<record id="general_ledger_wizard" model="ir.ui.view">
        <field name="name">General Ledger</field>
        <field name="model">general.ledger.report.wizard</field>
        <field name="arch" type="xml">
            <form>
                <group name="main_info">
                    <field name="company_id" options="{'no_create': True}" groups="base.group_multi_company"/>
                </group>
                <div attrs="{'invisible': [('not_only_one_unaffected_earnings_account', '=', True)]}">
                    <group name="filters">
                        <group name="date_range">
                            <field name="date_range_id"/>
                            <field name="date_from"/>
                            <field name="date_to"/>
                            <field name="fy_start_date" invisible="1"/>
                            <field name="journal_ids" widget="many2many_tags" options="{'no_create': True}"/>
                        </group>
                        <group name="other_filters">
                            <field name="target_move" widget="radio"/>
                            <field name="centralize"/>
                            <field name="hide_account_at_0"/>
                            <field name="foreign_currency"/>
                            <field name="show_analytic_tags"/>
                        </group>
                    </group>
                    <notebook>
                        <page string="Filter accounts">
                            <group col="4">
                                <field name="receivable_accounts_only"/>
                                <field name="payable_accounts_only"/>
                            </group>
                            <field name="account_ids" nolabel="1" widget="many2many_tags" options="{'no_create': True}"/>
                        </page>
                        <page string="Filter partners">
                            <field name="partner_ids" nolabel="1" widget="many2many_tags" options="{'no_create': True}"/>
                        </page>
                        <page string="Filter cost centers" groups="analytic.group_analytic_accounting">
                            <field name="cost_center_ids" nolabel="1" options="{'no_create': True}" groups="analytic.group_analytic_accounting"/>
                        </page>
                        <page string="Filter analytic tags">
                            <field name="analytic_tag_ids" widget="many2many_tags" nolabel="1" options="{'no_create': True}"/>
                        </page>
                    </notebook>
                </div>
                <div attrs="{'invisible': [('not_only_one_unaffected_earnings_account', '=', False)]}">
                    <field name="not_only_one_unaffected_earnings_account" invisible="1"/>
                    <group/>
                    <h4>General Ledger can be computed only if selected company have only one unaffected earnings account.</h4>
                    <group/>
                </div>
                <footer>
                    <div attrs="{'invisible': [('not_only_one_unaffected_earnings_account', '=', True)]}">
                        <button name="button_export_html" string="View" type="object" default_focus="1" class="oe_highlight"/>
                        or
                        <button name="button_export_pdf" string="Export PDF" type="object" default_focus="1" class="oe_highlight"/>
                        or
                        <button name="button_export_xlsx" string="Export XLSX" type="object"/>
                        or
                        <button string="Cancel" class="oe_link" special="cancel"/>
                    </div>
                    <div attrs="{'invisible': [('not_only_one_unaffected_earnings_account', '=', False)]}">
                        <button string="Cancel" class="oe_link" special="cancel"/>
                    </div>
                </footer>
            </form>
        </field>
    </record>

**Comment by pedrobaeza** [comment]
Restart your Odoo service and update again.
