### ISSUE TITLE
[11.0] account_financial_report: error in aged partner balance report

### ISSUE THREAD

**Issue by astirpe** [OCA/account-financial-reporting#553]
Reproduced in Runbot.

Steps to reproduce:

- Go to Invoicing -> Reporting -> OCA accounting reports -> Aged Partner Balance
- Set Show Move Line Details = True
- Click on View
- Click on one of the cells under column Residual or Current (value of cell must be not null)

Result:

```
Error:
Odoo Server Error

Traceback (most recent call last):
  File "/.repo_requirements/odoo/odoo/http.py", line 651, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/.repo_requirements/odoo/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/.repo_requirements/odoo/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/.repo_requirements/odoo/odoo/http.py", line 693, in dispatch
    result = self._call_function(**self.params)
  File "/.repo_requirements/odoo/odoo/http.py", line 318, in _call_function
    raise werkzeug.exceptions.BadRequest(msg % params)
werkzeug.exceptions.BadRequest: 400: Bad Request


```

**Comment by MiquelRForgeFlow** [comment]
Fixed in https://github.com/OCA/account-financial-reporting/pull/555. Could you check?
