### ISSUE TITLE
[12.0][BUG] account_financial_report: error clicking on currency

### ISSUE THREAD

**Issue by astirpe** [OCA/account-financial-reporting#581]
Reproduced in Runbot:

1. Open one report (eg.: General Ledger"). In the wizard click on "View".
2. Click on the currency symbol (eg: $).

Result:

```
Error:
Odoo Server Error

Traceback (most recent call last):
  File "/.repo_requirements/odoo/odoo/http.py", line 656, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/.repo_requirements/odoo/odoo/http.py", line 314, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/.repo_requirements/odoo/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/.repo_requirements/odoo/odoo/http.py", line 698, in dispatch
    result = self._call_function(**self.params)
  File "/.repo_requirements/odoo/odoo/http.py", line 322, in _call_function
    raise werkzeug.exceptions.BadRequest(msg % params)
werkzeug.exceptions.BadRequest: 400: Bad Request
```

**Comment by astirpe** [comment]
Seems not reproducible in General ledger anymore but I can still reproduce it in Trial Balance.
