### ISSUE TITLE
[12.0] account_financial_report: VAT Report - Tax details are not being fetched

### ISSUE THREAD

**Issue by adduzz** [OCA/account-financial-reporting#624]
Getting Odoo Client Error when clicked on any Tax amount

Error:
Uncaught Error: Object can not be converted to JSON

http://3390685-12-0-2bf0f6.runbot2.odoo-community.org/web/content/498-ebf2f8c/web.assets_backend.js:206
Traceback:
Error: Object can not be converted to JSON
    at F.toJSON (http://3390685-12-0-2bf0f6.runbot2.odoo-community.org/web/content/498-ebf2f8c/web.assets_backend.js:206:44)
    at F.toJSON (http://3390685-12-0-2bf0f6.runbot2.odoo-community.org/web/content/498-ebf2f8c/web.assets_backend.js:232:178)
    at F.toJSON (http://3390685-12-0-2bf0f6.runbot2.odoo-community.org/web/content/498-ebf2f8c/web.assets_backend.js:232:178)
    at Object.py.eval (http://3390685-12-0-2bf0f6.runbot2.odoo-community.org/web/content/498-ebf2f8c/web.assets_backend.js:274:329)
    at http://3390685-12-0-2bf0f6.runbot2.odoo-community.org/web/content/498-ebf2f8c/web.assets_backend.js:413:136
    at Function._.each._.forEach (http://3390685-12-0-2bf0f6.runbot2.odoo-community.org/web/content/492-bbc42fb/web.assets_common.js:12:558)
    at _.<computed> [as each] (http://3390685-12-0-2bf0f6.runbot2.odoo-community.org/web/content/492-bbc42fb/web.assets_common.js:69:526)
    at eval_domains (http://3390685-12-0-2bf0f6.runbot2.odoo-community.org/web/content/498-ebf2f8c/web.assets_backend.js:412:265)
    at Object.pyeval [as eval] (http://3390685-12-0-2bf0f6.runbot2.odoo-community.org/web/content/498-ebf2f8c/web.assets_backend.js:428:24)
    at Class._preprocessAction [as _super] (http://3390685-12-0-2bf0f6.runbot2.odoo-community.org/web/content/498-ebf2f8c/web.assets_backend.js:483:503)

**Comment by pedrobaeza** [comment]
Which Odoo version? Please try to reproduce the problem in OCA runbot.

**Comment by adduzz** [comment]
I am using v12 on runbot, above error is from OCA runbot

**Comment by pedrobaeza** [comment]
And detailed steps to reproduce the problem?

**Comment by adduzz** [comment]
I tried to normally generate VAT report by:
- select its menu item, Reporting --> VAT Report
- Enter dates and with Detail Taxes checked
- When report it displayed, clicked on any values in Net or Tax columns to view its details (not sure if it supports that)
- Odoo client error is popped up

I wanted to check details of the Net or Tax amount calculated based on which invoices/partners etc.

**Comment by pedrobaeza** [comment]
Thanks for the details. @sbidoul you were the one that added this report, isn't it?

**Comment by sbidoul** [comment]
I don't remember having worked on this report. Much less that it was clickable. Maybe a colleague of mine?

**Comment by pedrobaeza** [comment]
Not sure... I remember you mentioned about introducing this report as  `account_tax_balance` was not enough for you.

**Comment by sbidoul** [comment]
Must be someone else. I tend to do the tax reports with MIS Builder.

**Comment by pedrobaeza** [comment]
OK, my memory has tricked me. Then this issue will serve for whom do this.
