### ISSUE TITLE
[13.0] General Ledger Report crash

### ISSUE THREAD

**Issue by theopensourcerer** [OCA/account-financial-reporting#669]
```
Traceback (most recent call last):
  File "/opt/odoo13/odoo/odoo/addons/base/models/ir_http.py", line 229, in _dispatch
    result = request.dispatch()
  File "/opt/odoo13/odoo/odoo/http.py", line 804, in dispatch
    r = self._call_function(**self.params)
  File "/opt/odoo13/odoo/odoo/http.py", line 345, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo13/odoo/odoo/service/model.py", line 93, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo13/odoo/odoo/http.py", line 338, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo13/odoo/odoo/http.py", line 910, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo13/odoo/odoo/http.py", line 510, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo13/odoo/custom-addons/reporting-engine/report_xlsx/controllers/main.py", line 49, in report_routes
    reportname, docids, converter, **data
  File "/opt/odoo13/odoo/odoo/http.py", line 510, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo13/odoo/addons/web/controllers/main.py", line 1956, in report_routes
    html = report.with_context(context).render_qweb_html(docids, data=data)[0]
  File "/opt/odoo13/odoo/odoo/addons/base/models/ir_actions_report.py", line 757, in render_qweb_html
    data = self._get_rendering_context(docids, data)
  File "/opt/odoo13/odoo/odoo/addons/base/models/ir_actions_report.py", line 774, in _get_rendering_context
    data.update(report_model._get_report_values(docids, data=data))
  File "/opt/odoo13/odoo/custom-addons/account-financial-reporting/account_financial_report/report/general_ledger.py", line 657, in _get_report_values
    cost_center_ids,
  File "/opt/odoo13/odoo/custom-addons/account-financial-reporting/account_financial_report/report/general_ledger.py", line 451, in _get_period_ml_data
    acc_id = move_line["account_id"][0]
TypeError: 'bool' object is not subscriptable
```

Looking at the error I guess it might be because I have some move_lines in an invoice which have a display type of either "line_section" or "line_note". i.e. they are not real accounting moves - just notes on the invoice for printing/display to the customer?

I'm on a test database and just trying stuff out for now so happy to help with debugging if necessary.

**Comment by theopensourcerer** [comment]
Just FYI - I didn't want to create multiple issues but the Journal Ledger and Trial Balance reports in this module also crash. Not sure if they are all related or not. The errors are different. Shout if you want me to post these errors too.

**Comment by ernestotejeda** [comment]
Shouldn't this be closed since https://github.com/OCA/account-financial-reporting/pull/673 is mixed?
ping @pedrobaeza
