### ISSUE TITLE
[12.0] - Failed in module Mis builder Cash Flow when creating a report with multi company installation

### ISSUE THREAD

**Issue by alvarosalinero** [OCA/account-financial-reporting#703]
Hi,

I have an Odoo with multi company. When trying to generate a cash flow report, the following error appears:

<pre>
Traceback (most recent call last):
  File "/odoo/core/odoo/http.py", line 654, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/odoo/core/odoo/http.py", line 312, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/odoo/core/odoo/tools/pycompat.py", line 87, in reraise
    raise value
  File "/odoo/core/odoo/http.py", line 696, in dispatch
    result = self._call_function(**self.params)
  File "/odoo/core/odoo/http.py", line 344, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/odoo/core/odoo/service/model.py", line 97, in wrapper
    return f(dbname, *args, **kwargs)
  File "/odoo/core/odoo/http.py", line 337, in checked_call
    result = self.endpoint(*a, **kw)
  File "/odoo/core/odoo/http.py", line 939, in __call__
    return self.method(*args, **kw)
  File "/odoo/core/odoo/http.py", line 517, in response_wrap
    response = f(*args, **kw)
  File "/odoo/core/addons/web/controllers/main.py", line 962, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/odoo/core/addons/web/controllers/main.py", line 954, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/odoo/core/odoo/api.py", line 749, in call_kw
    return _call_kw_multi(method, model, args, kwargs)
  File "/odoo/core/odoo/api.py", line 736, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/odoo/extra_addons/mis_builder/models/mis_report_instance.py", line 817, in compute
    kpi_matrix = self._compute_matrix()
  File "/odoo/extra_addons/mis_builder/models/mis_report_instance.py", line 810, in _compute_matrix
    self._add_column(aep, kpi_matrix, period, period.name, description)
  File "/odoo/extra_addons/mis_builder/models/mis_report_instance.py", line 778, in _add_column
    aep, kpi_matrix, period, label, description
  File "/odoo/extra_addons/mis_builder/models/mis_report_instance.py", line 754, in _add_column_move_lines
    no_auto_expand_accounts=self.no_auto_expand_accounts,
  File "/odoo/extra_addons/mis_builder/models/mis_report.py", line 887, in _declare_and_compute_period
    expression_evaluator.aep_do_queries()
  File "/odoo/extra_addons/mis_builder/models/expression_evaluator.py", line 37, in aep_do_queries
    self.aml_model,
  File "/odoo/extra_addons/mis_builder/models/aep.py", line 353, in do_queries
    lazy=False,
  File "/odoo/core/odoo/models.py", line 2070, in read_group
    result = self._read_group_raw(domain, fields, groupby, offset=offset, limit=limit, orderby=orderby, lazy=lazy)
  File "/odoo/core/odoo/models.py", line 2093, in _read_group_raw
    query = self._where_calc(domain)
  File "/odoo/core/odoo/models.py", line 3869, in _where_calc
    e = expression.expression(domain, self)
  File "/odoo/core/odoo/osv/expression.py", line 672, in __init__
    self.parse()
  File "/odoo/core/odoo/osv/expression.py", line 853, in parse
    raise ValueError("Invalid field %r in leaf %r" % (left, str(leaf)))
ValueError: Invalid field 'line_type' in leaf "osv.ExtendedLeaf: ('line_type', '=', 'move_line') on account_move_line (ctx: )"
</pre>

When I test it on an Odoo without multi company, the error does not appear.

Is it a configuration problem of my Odoo with multi company?

Thanks in advance

**Comment by forvas** [comment]
Same problem here. It also happens with multicompany non-enabled. And I think it happens only when you create a new MIS report using Cash Flow template. The existing cash flow report works OK.

I am trying to check why they are adding `('line_type', '=', 'move_line')` to the domain of account move line searches, since that `move_line` value does not belong to the supplied list of the field selection values.

**Comment by javierjcf** [comment]
same probleme here in v13, line_type is not a field in account_move_line so it fails.
