### ISSUE TITLE
Error when update module, account_financial_report - v 13.0.1.3.1 from Local: 13.0.1.3.2 to Remote: 13.0.1.3.2

### ISSUE THREAD

**Issue by Rai-Mohammed** [OCA/account-financial-reporting#719]
Odoo Server Error
Traceback (most recent call last):
  File "/odoo_erp/odoo13ce/odoo13ce_server/odoo/http.py", line 624, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/odoo_erp/odoo13ce/odoo13ce_server/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/odoo_erp/odoo13ce/odoo13ce_server/odoo/tools/pycompat.py", line 14, in reraise
    raise value
  File "/odoo_erp/odoo13ce/odoo13ce_server/odoo/http.py", line 669, in dispatch
    result = self._call_function(**self.params)
  File "/odoo_erp/odoo13ce/odoo13ce_server/odoo/http.py", line 350, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/odoo_erp/odoo13ce/odoo13ce_server/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/odoo_erp/odoo13ce/odoo13ce_server/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/odoo_erp/odoo13ce/odoo13ce_server/odoo/http.py", line 915, in __call__
    return self.method(*args, **kw)
  File "/odoo_erp/odoo13ce/odoo13ce_server/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/odoo_erp/odoo13ce/odoo13ce_server/addons/web/controllers/main.py", line 1322, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/odoo_erp/odoo13ce/odoo13ce_server/addons/web/controllers/main.py", line 1314, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/odoo_erp/odoo13ce/odoo13ce_server/odoo/api.py", line 387, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/odoo_erp/odoo13ce/odoo13ce_server/odoo/api.py", line 374, in _call_kw_multi
    result = method(recs, *args, **kwargs)
TypeError: button_immediate_upgrade() takes 1 positional argument but 2 were given

**Comment by pedrobaeza** [comment]
It seems you have something incorrect in your end, but nothing to do with this module, as you can see in the stacktrace, and as the same problem happens with other modules.

Closing as no module issue.

**Comment by Rai-Mohammed** [comment]
I updated my installation from the cli and the two modules was updated without any problem or error, it happen my back-end is ok.  
./odoo13ce-bin --stop-after-init --config /usr/local/etc/odoo_erp/odoo13ce_server.conf  -u account_financial_report -d odoo13ce
./odoo13ce-bin --stop-after-init --config /usr/local/etc/odoo_erp/odoo13ce_server.conf  -u mis_builder -d odoo13ce

The reported error, its from the web interface for updating a module.

#719

**Comment by Rai-Mohammed** [comment]
I updated my installation from the cli and the two modules was updated without any problem or error, it happen my back-end is ok.  
./odoo13ce-bin --stop-after-init --config /usr/local/etc/odoo_erp/odoo13ce_server.conf  -u account_financial_report -d odoo13ce
./odoo13ce-bin --stop-after-init --config /usr/local/etc/odoo_erp/odoo13ce_server.conf  -u mis_builder -d odoo13ce

The reported error, its from the web interface for updating a module.
