### ISSUE TITLE
LINE 1: ALTER TABLE account_move ADD COLUMN IF NOT EXISTS financial_...

### ISSUE THREAD

**Issue by GunalanD95** [OCA/account-financial-reporting#813]
hi iam trying to install tax balance in my odoo 14 instance but while installing this error is coming 

error :
Error:
Odoo Server Error

Traceback (most recent call last):
  File "C:\Program Files (x86)\odoo-14\server\odoo\addons\base\models\ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "C:\Program Files (x86)\odoo-14\server\odoo\http.py", line 683, in dispatch
    result = self._call_function(**self.params)
  File "C:\Program Files (x86)\odoo-14\server\odoo\http.py", line 359, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "C:\Program Files (x86)\odoo-14\server\odoo\service\model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "C:\Program Files (x86)\odoo-14\server\odoo\http.py", line 347, in checked_call
    result = self.endpoint(*a, **kw)
  File "C:\Program Files (x86)\odoo-14\server\odoo\http.py", line 912, in __call__
    return self.method(*args, **kw)
  File "C:\Program Files (x86)\odoo-14\server\odoo\http.py", line 531, in response_wrap
    response = f(*args, **kw)
  File "C:\Program Files (x86)\odoo-14\server\odoo\addons\web\controllers\main.py", line 1393, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "C:\Program Files (x86)\odoo-14\server\odoo\addons\web\controllers\main.py", line 1381, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "C:\Program Files (x86)\odoo-14\server\odoo\api.py", line 396, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "C:\Program Files (x86)\odoo-14\server\odoo\api.py", line 383, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-72>", line 2, in button_immediate_install
  File "C:\Program Files (x86)\odoo-14\server\odoo\addons\base\models\ir_module.py", line 74, in check_and_log
    return method(self, *args, **kwargs)
  File "C:\Program Files (x86)\odoo-14\server\odoo\addons\base\models\ir_module.py", line 475, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "C:\Program Files (x86)\odoo-14\server\odoo\addons\base\models\ir_module.py", line 593, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "C:\Program Files (x86)\odoo-14\server\odoo\modules\registry.py", line 89, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "C:\Program Files (x86)\odoo-14\server\odoo\modules\loading.py", line 455, in load_modules
    loaded_modules, update_module, models_to_check)
  File "C:\Program Files (x86)\odoo-14\server\odoo\modules\loading.py", line 348, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "C:\Program Files (x86)\odoo-14\server\odoo\modules\loading.py", line 185, in load_module_graph
    getattr(py_module, pre_init)(cr)
  File "f:\todoencloud\addons\account_tax_balance\hooks.py", line 18, in pre_init_hook
    "ALTER TABLE account_move ADD COLUMN IF NOT EXISTS financial_type VARCHAR"
  File "f:\todoencloud\addons\slow_statement_logger\__init__.py", line 38, in execute
    return super().execute(query, params, log_exceptions)
  File "<decorator-gen-3>", line 2, in execute
  File "C:\Program Files (x86)\odoo-14\server\odoo\sql_db.py", line 101, in check
    return f(self, *args, **kwargs)
  File "C:\Program Files (x86)\odoo-14\server\odoo\sql_db.py", line 298, in execute
    res = self._obj.execute(query, params)
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Program Files (x86)\odoo-14\server\odoo\http.py", line 639, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "C:\Program Files (x86)\odoo-14\server\odoo\http.py", line 315, in _handle_exception
    raise exception.with_traceback(None) from new_cause
psycopg2.errors.SyntaxError: syntax error at or near "NOT"
LINE 1: ALTER TABLE account_move ADD COLUMN IF NOT EXISTS financial_...
                                               ^

**Comment by pedrobaeza** [comment]
You need a more modern Postgres version.

**Comment by GunalanD95** [comment]
hi mine is psql (PostgreSQL) 13.3

**Comment by pedrobaeza** [comment]
Are you sure? Such syntax should be accepted then. Try in a psql to see the version and execute the same query.

**Comment by GunalanD95** [comment]
yup same version

**Comment by pedrobaeza** [comment]
Definitively there's something wrong with your deployment, as it highlights the issue you have put on Odoo. Deploy it correctly.

**Comment by GunalanD95** [comment]
yeah i think the same , will do it
