### ISSUE TITLE
[account_financial_report] Memory problems setting filters to reports

### ISSUE THREAD

**Issue by InformaticaOdeon** [OCA/account-financial-reporting#814]
Hello, we got the following error when set filters to differents reports

Odoo Server Error
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 624, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 310, in _handle_exception
    raise pycompat.reraise(type(exception), exception, sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/odoo/tools/pycompat.py", line 14, in reraise
    raise value
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 669, in dispatch
    result = self._call_function(**self.params)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 350, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 339, in checked_call
    result = self.endpoint(*a, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 915, in __call__
    return self.method(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 1339, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 1331, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 387, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/usr/lib/python3/dist-packages/odoo/api.py", line 374, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 6251, in onchange
    record._onchange_eval(name, field_onchange[name], result)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 6030, in _onchange_eval
    method_res = method(self)
  File "/mnt/extra-addons/account-financial-reporting/account_financial_report/wizard/general_ledger_wizard.py", line 106, in on_change_account_range
    [("code", "in", [x for x in range(start_range, end_range + 1)])]
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 1648, in search
    res = self._search(args, offset=offset, limit=limit, order=order, count=count)
  File "/usr/lib/python3/dist-packages/odoo/models.py", line 4499, in _search
    self._cr.execute(query_str, where_clause_params)
  File "/usr/lib/python3/dist-packages/odoo/sql_db.py", line 173, in wrapper
    return f(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/odoo/sql_db.py", line 250, in execute
    res = self._obj.execute(query, params)
psycopg2.InternalError: invalid memory alloc request size 1073741824

We have detected the following problem in the account-financial-reporting module, specifically in the code of the following files:

account-financial-reporting / account_financial_report / wizard / aged_partner_balance_wizard.py
account-financial-reporting / account_financial_report / wizard / general_ledger_wizard.py
account-financial-reporting / account_financial_report / wizard / open_items_wizard.py
account-financial-reporting / account_financial_report / wizard / trial_balance_wizard.py

The same problem appears in all of them.

The following sentence exists in code, according to the file:

self.account_ids = self.env ["account.account"]. search (
[("code", "in", [x for x in range (start_range, end_range + 1)])]
)

Or this one.

self.account_ids = self.env ["account.account"]. search (
[
("code", "in", [x for x in range (start_range, end_range + 1)]),
            ("reconcile", "=", True),
        ]
    )

If for example we have the values:

start_range = 10000000
end_range = 30000000

An attempt is made to construct a SELECT statement with an IN operator with many values, so many that the size of the statement string causes memory overflow.

SELECT ... FROM ... WHERE .... code IN (10000000, 10000001, 10000002, 10000003, 10000004, .........., 30000000)

We have tried this alternative with which we have obtained the correct result without producing memory errors.

self.account_ids = self.env ["account.account"]. search (
[("code", "> =", start_range), ("code", "<=", end_range)]
    )

Can you review it in case it is convenient to modify this module?

Thanks,
Greetings.

**Comment by mof-landoo** [comment]
Same issue here, trying to get a General Ledger report, if the account range is too large (ie. 6000000 to 7000000)

![error in general ledger](https://user-images.githubusercontent.com/74420869/151156006-07ce0ea9-944b-4448-88e1-cbe15dc4d515.png)

When we select the second value it starts loading and after some time (less than one minute) we get this error in the log:

2022-01-26 11:07:07,517 1381772 ERROR copia_pro_15_11_2021 odoo.sql_db: bad query: SELECT "account_account".id FROM "account_account" LEFT JOIN "res_company" AS "account_account__company_id" ON ("account_account"."company_id" = "account_account__company_id"."id") WHERE ("account_account"."code" in ('60000000','60000001','60000002','60000003','60000004','60000005','60000006','60000007',...

Connection resets (message connection lost | you are back online) and nothing else happens. Checking htop command we see that the RAM starts to get higher and higher until it reachs the limit (6G in our case). This database is quite new and we don't have a lot of data. 

We have tried to set different parameters in odoo conf file and nginx, and also updated dependencies of account_financial_report with same result, 

Any ideas? Thank you 

ping @joao-p-marques

**Comment by alexis-via** [comment]
I have also experienced this bug today on odoo v14.0 with up-to-date code from OCA/account-financial-reporting
