### ISSUE TITLE
[13] Cant gerenate pdf reports

### ISSUE THREAD

**Issue by carlosmaug** [OCA/account-financial-reporting#817]
Hi

In Odoo 13, Regardless of the report I choose I always got the same error. "Form content is missing, this report cannot be printed."
If it seems odoo do not retrieve necessary data to generate the reports.
I can print invoices an many other PDFs
If I go to Accounting -> reports -> accounting reports (OCA) I can see the reports and export them in XLSX but if I try to print any of them always I got an error like this:

Error:
Odoo Server Error

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 2053, in report_download
    response = self.report_routes(reportname, converter=converter, context=context, **data)
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo/modulos_activos/report_xlsx_helper/controllers/main.py", line 56, in report_routes
    reportname, docids, converter, **data
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo/modulos_activos/report_xlsx/controllers/main.py", line 49, in report_routes
    reportname, docids, converter, **data
  File "/usr/lib/python3/dist-packages/odoo/http.py", line 515, in response_wrap
    response = f(*args, **kw)
  File "/usr/lib/python3/dist-packages/odoo/addons/web/controllers/main.py", line 1984, in report_routes
    pdf = report.with_context(context).render_qweb_pdf(docids, data=data)[0]
  File "/usr/lib/python3/dist-packages/odoo/addons/account/models/ir_actions_report.py", line 47, in render_qweb_pdf
    return super().render_qweb_pdf(res_ids=res_ids, data=None)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_actions_report.py", line 769, in render_qweb_pdf
    html = self.with_context(context).render_qweb_html(res_ids, data=data)[0]
  File "/home/odoo/modulos_activos/account_financial_report/models/ir_actions_report.py", line 19, in render_qweb_html
    return super(IrActionsReport, obj).render_qweb_html(docids, data)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_actions_report.py", line 809, in render_qweb_html
    data = self._get_rendering_context(docids, data)
  File "/usr/lib/python3/dist-packages/odoo/addons/base/models/ir_actions_report.py", line 826, in _get_rendering_context
    data.update(report_model._get_report_values(docids, data=data))
  File "/home/odoo/modulos_activos/account_financial_report/report/general_ledger.py", line 756, in _get_report_values
    wizard_id = data["wizard_id"]
KeyError: 'wizard_id'

**Comment by pedrobaeza** [comment]
Update your Odoo code. It's not this module fault. See https://github.com/odoo/odoo/pull/76696

**Comment by carlosmaug** [comment]
I have updated odoo code and now all woks fine. Tank you very much
