### ISSUE TITLE
14.0 Does not permit the installation of account-financial-reporting 

### ISSUE THREAD

**Issue by OAlarconCast** [OCA/account-financial-reporting#828]
Module

account-financial-reporting

## Describe the bug
After the appropriate installation in Odoo 14 Community instance did not permit the installation

## To Reproduce
**Affected versions**: 14:0

1. Git clone grom OCA Github taking in consideration the installation of prerequisites 
2. Using VPS Server
3. Update odoo.conf
4. Systemctl Restart odoo14.service
5. In the instance Update applications
6. Try to install the module
7. Failed with the following messsage

Error:
Odoo Server Error

Traceback (most recent call last):
  File "/opt/cfyemprend01/14.0/odoo/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/opt/cfyemprend01/14.0/odoo/odoo/http.py", line 684, in dispatch
    result = self._call_function(**self.params)
  File "/opt/cfyemprend01/14.0/odoo/odoo/http.py", line 360, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/cfyemprend01/14.0/odoo/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/cfyemprend01/14.0/odoo/odoo/http.py", line 348, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/cfyemprend01/14.0/odoo/odoo/http.py", line 913, in __call__
    return self.method(*args, **kw)
  File "/opt/cfyemprend01/14.0/odoo/odoo/http.py", line 532, in response_wrap
    response = f(*args, **kw)
  File "/opt/cfyemprend01/14.0/odoo/addons/web/controllers/main.py", line 1393, in call_button
    action = self._call_kw(model, method, args, kwargs)
  File "/opt/cfyemprend01/14.0/odoo/addons/web/controllers/main.py", line 1381, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/opt/cfyemprend01/14.0/odoo/odoo/api.py", line 396, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/opt/cfyemprend01/14.0/odoo/odoo/api.py", line 383, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "<decorator-gen-71>", line 2, in button_immediate_install
  File "/opt/cfyemprend01/14.0/odoo/odoo/addons/base/models/ir_module.py", line 74, in check_and_log
    return method(self, *args, **kwargs)
  File "/opt/cfyemprend01/14.0/odoo/odoo/addons/base/models/ir_module.py", line 475, in button_immediate_install
    return self._button_immediate_function(type(self).button_install)
  File "/opt/cfyemprend01/14.0/odoo/odoo/addons/base/models/ir_module.py", line 593, in _button_immediate_function
    modules.registry.Registry.new(self._cr.dbname, update_module=True)
  File "/opt/cfyemprend01/14.0/odoo/odoo/modules/registry.py", line 89, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/opt/cfyemprend01/14.0/odoo/odoo/modules/loading.py", line 461, in load_modules
    loaded_modules, update_module, models_to_check)
  File "/opt/cfyemprend01/14.0/odoo/odoo/modules/loading.py", line 349, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/opt/cfyemprend01/14.0/odoo/odoo/modules/loading.py", line 188, in load_module_graph
    model_names = registry.load(cr, package)
  File "/opt/cfyemprend01/14.0/odoo/odoo/modules/registry.py", line 231, in load
    model = cls._build_model(self, cr)
  File "/opt/cfyemprend01/14.0/odoo/odoo/models.py", line 604, in _build_model
    model.__init__(pool, cr)
  File "/opt/cfyemprend01/14.0/extra-addons/oca/account-financial-reporting/account_financial_report/report/abstract_report_xlsx.py", line 14, in __init__
    self.sheet = None
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/cfyemprend01/14.0/odoo/odoo/http.py", line 640, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/opt/cfyemprend01/14.0/odoo/odoo/http.py", line 316, in _handle_exception
    raise exception.with_traceback(None) from new_cause
AttributeError: 'report.account_financial_report.abstract_report_xlsx' object has no attribute 'sheet'
**Expected behavior**

**Additional context**
Add any other context about the problem here. (e.g. OS, Python version, ...)

**Comment by pedrobaeza** [comment]
You have missed the installation of the `xlsxwriter` Python library in your environment (or it's not a correct one). Closing as no module issue, but a deployment one.

**Comment by wm-cortex** [comment]
> You have missed the installation of the `xlsxwriter` Python library in your environment (or it's not a correct one). Closing as no module issue, but a deployment one.

I'm getting the same error in Odoo 14, I checked the xlsxwriter and it's installed with version mentioned in Odoo 14 Requirements 
V1.1.2, I also tried the latest version and still getting the same error. I'm using python 3.6

**Comment by beneditomonteiro** [comment]
Where can I see the xlsxwriter correct version to install in my environment? Thanks.

python3-xlsxwriter is already the newest version (1.1.2-0.2).
Requirement already satisfied: xlrd in /home/bmonteiro/.local/lib/python3.8/site-packages (2.0.1)


It doesn´t seems to be the version of the xlsxwriter, it seems that something was not imported.

class AbstractReportXslx(models.AbstractModel):
    _name = "report.account_financial_report.abstract_report_xlsx"
    _description = "Abstract XLSX Account Financial Report"
    _inherit = "report.report_xlsx.abstract"

    def __init__(self, pool, cr):
        # main sheet which will contains report
        self.sheet = None
